/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leven_ffmpeg_jni_VideoPlayerDecode */

#ifndef _Included_com_leven_ffmpeg_jni_VideoPlayerDecode
#define _Included_com_leven_ffmpeg_jni_VideoPlayerDecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leven_ffmpeg_jni_VideoPlayerDecode
 * Method:    Getcpu
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leven_ffmpeg_jni_VideoPlayerDecode_Getcpu
  (JNIEnv *, jclass);

/*
 * Class:     com_leven_ffmpeg_jni_VideoPlayerDecode
 * Method:    VideoPlayer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_leven_ffmpeg_jni_VideoPlayerDecode_VideoPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_leven_ffmpeg_jni_VideoPlayerDecode
 * Method:    VideoPlayerPauseOrPlay
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_leven_ffmpeg_jni_VideoPlayerDecode_VideoPlayerPauseOrPlay
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_leven_ffmpeg_jni_VideoPlayerDecode
 * Method:    VideoPlayerStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leven_ffmpeg_jni_VideoPlayerDecode_VideoPlayerStop
  (JNIEnv *, jclass);

/*
 * Class:     com_leven_ffmpeg_jni_VideoPlayerDecode
 * Method:    VideoPlayerChangeVideo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_leven_ffmpeg_jni_VideoPlayerDecode_VideoPlayerChangeVideo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_leven_ffmpeg_jni_VideoPlayerDecode
 * Method:    GlCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leven_ffmpeg_jni_VideoPlayerDecode_GlCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_leven_ffmpeg_jni_VideoPlayerDecode
 * Method:    GlInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_leven_ffmpeg_jni_VideoPlayerDecode_GlInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_leven_ffmpeg_jni_VideoPlayerDecode
 * Method:    GlRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_leven_ffmpeg_jni_VideoPlayerDecode_GlRender
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
